# -*- coding: utf-8 -*-
"""test_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ss06ZVwB250odV18fJNf0yNrTQnkTaB_
"""

def test_sample():
    assert 2 + 2 == 4